language: java

jdk:
    - openjdk11
     
os:
    - linux
    
dist:
    - xenial
    
git:
  depth: false
    
addons:
  sonarcloud:
    organization: "gulixciurli"
    token: "da8e8c62cfcfc35f8e7d2a16c2df3e636da632f6"

script:
    - ant build
    - sonar-scanner
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=gulixciurli_check
    - mvn clean verify -P coverageProfile
    - mkdir -p target/site/
    - java -jar lib/jacococli.jar report target/jacoco.exec --classfiles lib/jcs-1.3.jar --sourcefiles lib/jcs-1.3/ --html target/site/ --xml target/site/file.xml --csv target/site/file.csv
    - mvn verify sonar:sonar
    - ls target/site/
