language: java

jdk:
    - openjdk11
     
os:
    - linux
    
dist:
    - xenial
    
git:
  depth: false
    
addons:
  sonarcloud:
    organization: "gulixciurli"
    token:
      secure: "KevwJR4duUfLbCV7ZpEJFbiD9iOldIGMF3UUsxHPIkCyWrmb7CB/2NURqw0PqtDZ3P3/vzSAoMFFc9kbR05XHeRZWVTrwRL+QcdlWFn+MG7v3AIZDJUoljWC8bf1DX11ZYiya6JKGD89HqtUXk3chUAlkLJ9XCjXq+y+EiSBZYl0pQL6/iTHnJWnAGgglnSWIuz6A8bPDSYUd9RMsJupHJjLB2riOXt/keNoYVul/6SI6N/PuSDgltPBIreA72sRVo5bZoSyxJJUi/fmir/EEZhsuWR/G/MVjNppYqAA/zzhzFl7o043IcbanvrQs2BEoze4bNoMEKq2i5MQn2jlobB472iJedo69R9H9Ln2p5nakhe2S73aSZLzoa6WlurYe3HmZLFeJ9+bGM46DUp2KfATC1lCOHA1GOnV5xz7GR083EhmexFPdc21dMljWB7WeUikoSryVH4mkmKZIlz8ZqiofvXptAIyY++8xDA/coKfZSlGoQVchlty4Ea173Q8RdxSnZmuCSjbgQs+KMGyfQ55hPH59mWCcU3zxWXAbthNBhzRlqCSNbBJVajsQT4N0h/KBO2ISBGCWrPCGyTASydpZ1R7D3F8/hXNysBlEVv2XGcJ7Zkv7E9ljocmaFB5q5jSDy2I2KPBabYj1QgeKQZ1ZnPRwi3eKRIYb3hoNK0=" # encrypted value of your token

script:
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=gulixciurli_check
    - mvn clean verify -P coverageProfile
    - mkdir -p target/site/
    - java -jar lib/jacococli.jar report target/jacoco.exec --classfiles lib/jcs-1.3.jar --sourcefiles lib/jcs-1.3/ --html target/site/ --xml target/site/file.xml --csv target/site/file.csv
    - mvn verify sonar:sonar
    - ls target/site/
